import { FormEvent, useEffect, useState } from 'react';
import { Check, Copy, FilePlus2 } from 'lucide-react';
import { api } from '../api';
import { Letter, LetterType } from '../types';
import { ErrorMessage, Spinner } from '../components/States';

const displayDate = (date: string) => new Date(`${date}T00:00:00`).toLocaleDateString('id-ID');

export function CreateLetter() {
  const [departments, setDepartments] = useState<string[]>([]); const [department, setDepartment] = useState(''); const [type, setType] = useState<LetterType | ''>(''); const [subject, setSubject] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [created, setCreated] = useState<Letter>(); const [copied, setCopied] = useState(false);
  useEffect(() => { api.departments().then(setDepartments).catch(e => setError(e instanceof Error ? e.message : 'Gagal memuat departemen.')).finally(() => setLoading(false)); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (!department || !type || !subject.trim()) { setError('Lengkapi semua field yang wajib diisi.'); return; } setSubmitting(true); try { setCreated(await api.create({ department, type, subject: subject.trim() })); } catch (e) { setError(e instanceof Error ? e.message : 'Nomor surat gagal dibuat.'); } finally { setSubmitting(false); } };
  const copy = async () => { if (!created) return; await navigator.clipboard.writeText(created.letterNumber); setCopied(true); setTimeout(() => setCopied(false), 1800); };
  if (created) return <div className="mx-auto max-w-2xl"><div className="mb-5 flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center bg-green-50 text-bmc-success"><Check size={19}/></div><div><h1 className="text-xl font-semibold">Nomor Surat Berhasil Dibuat</h1><p className="text-sm text-bmc-muted">Data telah tersimpan di sistem.</p></div></div><div className="border border-bmc-border bg-white p-6 sm:p-8"><div className="border-l-2 border-bmc-red bg-gray-50 px-4 py-4 text-lg font-semibold leading-relaxed">{created.letterNumber}</div><div className="mt-7 grid gap-5 border-b border-bmc-border pb-6 sm:grid-cols-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-bmc-muted">Departemen</p><p className="mt-1 text-sm font-medium">{created.department}</p></div><div><p className="text-xs font-semibold uppercase tracking-wide text-bmc-muted">Jenis</p><p className="mt-1 text-sm font-medium">{created.type === 'INTERNAL' ? 'Internal' : 'External'}</p></div><div><p className="text-xs font-semibold uppercase tracking-wide text-bmc-muted">Tanggal</p><p className="mt-1 text-sm font-medium">{displayDate(created.letterDate)}</p></div></div><div className="mt-6"><button onClick={copy} className="btn-primary"><Copy size={16}/>{copied ? 'Nomor surat berhasil disalin.' : 'Copy Nomor Surat'}</button></div></div></div>;
  return <div className="mx-auto max-w-2xl"><div className="mb-6"><h1 className="text-2xl font-semibold">Buat Nomor Surat</h1><p className="mt-1 text-sm text-bmc-muted">Lengkapi informasi di bawah untuk mendapatkan nomor surat BMC.</p></div>{error && <div className="mb-5"><ErrorMessage message={error}/></div>}<form onSubmit={submit} className="border border-bmc-border bg-white p-5 sm:p-7"><div className="space-y-5"><label className="block"><span className="mb-2 block text-sm font-semibold">Departemen *</span><select required disabled={loading || submitting} value={department} onChange={e => setDepartment(e.target.value)} className="field"><option value="">{loading ? 'Memuat departemen...' : 'Pilih departemen'}</option>{departments.map(d => <option key={d}>{d}</option>)}</select></label><label className="block"><span className="mb-2 block text-sm font-semibold">Jenis Surat *</span><select required disabled={submitting} value={type} onChange={e => setType(e.target.value as LetterType)} className="field"><option value="">Pilih jenis surat</option><option value="INTERNAL">Internal</option><option value="EXTERNAL">External</option></select></label><label className="block"><div className="mb-2 flex justify-between"><span className="text-sm font-semibold">Subject / Reason *</span><span className="text-xs text-bmc-muted">{subject.length} / 500</span></div><textarea required maxLength={500} disabled={submitting} value={subject} onChange={e => setSubject(e.target.value)} rows={5} className="field resize-y" placeholder="Masukkan alasan atau subject surat"/></label></div><div className="mt-7 flex justify-end"><button disabled={submitting} className="btn-primary"><FilePlus2 size={16}/>{submitting ? 'Menyimpan...' : 'Buat Nomor Surat'}</button></div></form></div>;
}
