CREATE TABLE EmployeeAccess (
    NIP VARCHAR(50) NOT NULL PRIMARY KEY,
    Role VARCHAR(30) NOT NULL CONSTRAINT DF_EmployeeAccess_Role DEFAULT 'ADMIN',
    IsActive BIT NOT NULL CONSTRAINT DF_EmployeeAccess_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_EmployeeAccess_CreatedAt DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_EmployeeAccess_UpdatedAt DEFAULT SYSDATETIME(),
    CONSTRAINT CK_EmployeeAccess_Role CHECK (Role IN ('ADMIN', 'HR'))
);

INSERT INTO EmployeeAccess (NIP, Role, IsActive)
SELECT '3490', 'ADMIN', 1
WHERE NOT EXISTS (SELECT 1 FROM EmployeeAccess WHERE NIP = '3490');
